### PR TITLE
Expose and document SlideIndicator contract

### PR DESCRIPTION
**Pull request by DDavidPrime**
This PR addresses the issue mentioned in #35 

Besides exposing the `SlideIndicator`, I've added documentation for it as well, since it may come useful to people who would like to make their own implementations of the slide indicators.

### CODE REVIEW

**Comment by nixrajput** [comment]
Hi @DDavidPrime,

Thank you for the PR.

Can you please add the usage process to the documentation too?
It would be very helpful for the users to implement it with ease.
You can add it after this [section](https://github.com/nixrajput/flutter_carousel_widget?tab=readme-ov-file#carousel-controller) in the README file.

Thanks & regards,
Nikhil

**Comment by DDavidPrime** [comment]
Of course! I'm a bit busy, but will try to have it done in the following day or two. 🫡

**Comment by nixrajput** [comment]
Okay, then I will merge the PR and I am also planning to release the next update after some bug fixes, so please try to do it ASAP.

Thanks.

**Comment by DDavidPrime** [comment]
@nixrajput All done! Please review it and let me know if there's something else to fix/update/add. 🙌🏼

**Comment by nixrajput** [comment]
@DDavidPrime thank you for the contribution to the project.

**Pull request merged**
